[tool.poetry]
name = "bright-data-layer"
version = "0.1.0"
description = "Lambda layer dependencies"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"
pendulum = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"